name: sc-dense
channels:
  - defaults
  - bioconda
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _x86_64-microarch-level=3=2_zen2
  - alsa-lib=1.2.14=hb9d3cd8_0
  - anndata=0.11.4=pyhd8ed1ab_0
  - arpack=3.9.1=nompi_hf03ea27_102
  - array-api-compat=1.11.2=pyh29332c3_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - awkward=2.8.3=pyhe01879c_1
  - awkward-cpp=46=py311hf8c1401_300
  - blas=2.131=openblas
  - blas-devel=3.9.0=31_h1ea3ea9_openblas
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py311hfdbb021_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - celltypist=1.6.3=pyhdfd78af_0
  - certifi=2025.4.26=pyhd8ed1ab_0
  - cffi=1.17.1=py311hf29c0ef_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.2=py311hd18a35c_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.14=py311hfdbb021_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=h5888daf_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.7.0=h5888daf_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.57.0=py311h2dc5d0c_0
  - freetype=2.13.3=h48d6fc4_0
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.13=h59595ed_1003
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.13.0=nompi_py311hb639ac4_100
  - harfbuzz=11.1.0=h3beb420_0
  - hdf5=1.14.3=nompi_h2d575fe_109
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - igraph=0.10.15=he44f51b_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.30.0=pyh707e725_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.4.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py311hd18a35c_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - legacy-api-wrap=1.4.1=pyhd8ed1ab_0
  - leidenalg=0.10.2=py311hb755f60_0
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.3=h59595ed_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=31_he106b2a_openblas
  - libclang-cpp20.1=20.1.3=default_h1df26ce_0
  - libclang13=20.1.3=default_he06ed0a_0
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.13.0=h332b0f4_0
  - libdeflate=1.23=h86f0d12_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.1=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h767d61c_2
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblapacke=3.9.0=31_he2f377e_openblas
  - libleidenalg=0.11.1=h00ab1b0_0
  - libllvm20=20.1.3=he9d0ab4_0
  - liblzma=5.8.1=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.47=h943b412_0
  - libpq=17.4=h27ae623_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.49.1=hee588c1_2
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtiff=4.7.0=hd9ff511_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.8.1=hc4a0caf_0
  - libxml2=2.13.7=h4bc477f_1
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.44.0=py311h9c9ff8c_1
  - matplotlib=3.10.1=py311h38be061_0
  - matplotlib-base=3.10.1=py311h2b939e6_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=9.2.0=h266115a_0
  - mysql-libs=9.2.0=he0572af_0
  - natsort=8.4.0=pyh29332c3_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - numba=0.61.2=py311h4e1c48f_0
  - numpy=1.26.4=py311h24aa872_0
  - numpy-base=1.26.4=py311hbfb1bba_0
  - openblas=0.3.29=pthreads_h6ec200e_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.9=he970967_0
  - openpyxl=3.1.5=py311h50c5138_1
  - openssl=3.5.0=h7b32b05_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py311h7db5c69_3
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=hba22ea6_2
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py311h1322bbf_0
  - pip=25.0.1=pyh8b19718_0
  - pixman=0.44.2=h29eaf8c_0
  - platformdirs=4.3.7=pyh29332c3_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py311h9ecbd09_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyside6=6.9.0=py311h9053184_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.11=h9e4cc4f_2_cpython
  - python-annoy=1.17.3=py311hfdbb021_2
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-igraph=0.11.8=py311h9806173_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=7_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=26.4.0=py311h7deb3e3_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.0=h6441bc3_1
  - readline=8.2=h8c095d6_2
  - requests=2.32.3=pyhd8ed1ab_1
  - scanpy=1.10.4=pyhd8ed1ab_0
  - scikit-learn=1.6.1=py311h57cc02b_0
  - scipy=1.15.2=py311h8f841c2_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - session-info=1.0.0=pyhd8ed1ab_0
  - setuptools=79.0.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.4=py311h9f3472d_0
  - stdlib-list=0.11.1=pyhd8ed1ab_0
  - tbb=2022.1.0=h4ce085d_0
  - texttable=1.7.0=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.2=py311h9ecbd09_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025b=h78e105d_0
  - umap-learn=0.5.7=py311h38be061_1
  - unicodedata2=16.0.0=py311h9ecbd09_0
  - urllib3=2.4.0=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstandard=0.23.0=py311h9ecbd09_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - adjusttext==1.3.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - airr==1.5.1
      - attrs==25.3.0
      - bbknn==1.6.0
      - chex==0.1.90
      - cython==3.1.3
      - dnspython==2.8.0
      - docrep==0.3.2
      - etils==1.13.0
      - fa2-modified==0.3.10
      - filelock==3.13.1
      - flax==0.11.2
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - future==1.0.0
      - grpcio==1.74.0
      - humanize==4.13.0
      - hyperopt==0.1.2
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - jax==0.6.2
      - jaxlib==0.6.2
      - jinja2==3.1.4
      - levenshtein==0.27.1
      - lightning==2.5.5
      - lightning-utilities==0.15.2
      - logomaker==0.8.7
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - ml-collections==1.1.0
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - msgpack==1.1.1
      - mudata==0.3.2
      - multidict==6.6.4
      - multipledispatch==1.0.0
      - muon==0.1.7
      - numpyro==0.19.0
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - opt-einsum==3.4.0
      - optax==0.2.5
      - orbax-checkpoint==0.11.25
      - pluggy==1.6.0
      - pooch==1.8.2
      - propcache==0.3.2
      - protobuf==6.31.1
      - pymongo==4.15.0
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytest==8.4.1
      - python-levenshtein==0.27.1
      - pytorch-lightning==2.5.5
      - pyyaml==6.0.2
      - rapidfuzz==3.13.0
      - rich==14.1.0
      - scikit-misc==0.5.1
      - scikit-posthocs==0.11.4
      - scirpy==0.22.0
      - scvi-tools==1.3.3
      - simplejson==3.20.1
      - sparse==0.17.0
      - squarify==0.4.4
      - sympy==1.13.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.76
      - thresholdpy==0.1.5
      - toolz==1.0.0
      - torch==2.7.0+cu118
      - torchaudio==2.7.0+cu118
      - torchmetrics==1.8.2
      - torchvision==0.22.0+cu118
      - treescope==0.1.10
      - triton==3.3.0
      - werkzeug==3.1.3
      - xarray==2025.9.0
      - xlrd==2.0.2
      - yamlordereddictloader==0.4.2
      - yarl==1.20.1
